#!/bin/bash

# Configuration management for Pauly CLI

CONFIG_FILE="$HOME/.config/pauly/config"
CONFIG_DIR="$HOME/.config/pauly"

# Default values
DEFAULT_EMAIL=""
DEFAULT_PROJECTS_DIR="$HOME/Projects"
DEFAULT_MAX_LOG_SIZE_MB=10
DEFAULT_MAX_LOG_FILES=5
DEFAULT_HEALTHCHECK_URL=""

# SMTP defaults
DEFAULT_SMTP_HOST="smtp.gmail.com"
DEFAULT_SMTP_PORT=587
DEFAULT_SMTP_USER=""
DEFAULT_SMTP_PASSWORD=""

# IMAP defaults (for receiving task emails)
DEFAULT_IMAP_HOST="imap.gmail.com"
DEFAULT_IMAP_PORT=993
DEFAULT_ALLOWED_SENDERS=""

# Dev mode defaults
DEFAULT_DEV_PROJECT_DIR=""

# GitHub tasks defaults
DEFAULT_GITHUB_TASKS_REPO=""
DEFAULT_GITHUB_TASKS_LABEL="pauly"

# Auto-fix defaults
DEFAULT_AUTOFIX_ENABLED="false"
DEFAULT_AUTOFIX_SCRIPTS="all"
DEFAULT_AUTOFIX_MAX_ATTEMPTS=1
DEFAULT_AUTOFIX_BRANCH_PREFIX="autofix"

# Config files
MSMTP_CONFIG="$HOME/.msmtprc"

# ==========================================
# Config File Management
# ==========================================

ensure_config_dir() {
    mkdir -p "$CONFIG_DIR"
}

load_config() {
    ensure_config_dir

    # Set defaults
    EMAIL="${DEFAULT_EMAIL}"
    PROJECTS_DIR="${DEFAULT_PROJECTS_DIR}"
    MAX_LOG_SIZE_MB="${DEFAULT_MAX_LOG_SIZE_MB}"
    MAX_LOG_FILES="${DEFAULT_MAX_LOG_FILES}"
    HEALTHCHECK_URL="${DEFAULT_HEALTHCHECK_URL}"

    # SMTP defaults
    SMTP_HOST="${DEFAULT_SMTP_HOST}"
    SMTP_PORT="${DEFAULT_SMTP_PORT}"
    SMTP_USER="${DEFAULT_SMTP_USER}"
    SMTP_PASSWORD="${DEFAULT_SMTP_PASSWORD}"

    # IMAP defaults
    IMAP_HOST="${DEFAULT_IMAP_HOST}"
    IMAP_PORT="${DEFAULT_IMAP_PORT}"
    ALLOWED_SENDERS="${DEFAULT_ALLOWED_SENDERS}"

    # Dev mode defaults
    DEV_PROJECT_DIR="${DEFAULT_DEV_PROJECT_DIR}"

    # GitHub tasks defaults
    GITHUB_TASKS_REPO="${DEFAULT_GITHUB_TASKS_REPO}"
    GITHUB_TASKS_LABEL="${DEFAULT_GITHUB_TASKS_LABEL}"

    # Auto-fix defaults
    AUTOFIX_ENABLED="${DEFAULT_AUTOFIX_ENABLED}"
    AUTOFIX_SCRIPTS="${DEFAULT_AUTOFIX_SCRIPTS}"
    AUTOFIX_MAX_ATTEMPTS="${DEFAULT_AUTOFIX_MAX_ATTEMPTS}"
    AUTOFIX_BRANCH_PREFIX="${DEFAULT_AUTOFIX_BRANCH_PREFIX}"

    # Load from file if exists
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
    fi
}

save_config() {
    ensure_config_dir

    cat > "$CONFIG_FILE" << EOF
# Pauly Configuration
# Generated: $(date)

# Email for notifications and alerts
EMAIL="$EMAIL"

# Directory to scan for git repos and projects
PROJECTS_DIR="$PROJECTS_DIR"

# Log rotation settings
MAX_LOG_SIZE_MB=$MAX_LOG_SIZE_MB
MAX_LOG_FILES=$MAX_LOG_FILES

# Healthchecks.io ping URL (optional)
HEALTHCHECK_URL="$HEALTHCHECK_URL"

# SMTP Configuration
SMTP_HOST="$SMTP_HOST"
SMTP_PORT=$SMTP_PORT
SMTP_USER="$SMTP_USER"
SMTP_PASSWORD="$SMTP_PASSWORD"

# IMAP Configuration (for email tasks)
IMAP_HOST="$IMAP_HOST"
IMAP_PORT=$IMAP_PORT
ALLOWED_SENDERS="$ALLOWED_SENDERS"

# Dev Mode Configuration
DEV_PROJECT_DIR="$DEV_PROJECT_DIR"

# GitHub Tasks Configuration
GITHUB_TASKS_REPO="$GITHUB_TASKS_REPO"
GITHUB_TASKS_LABEL="$GITHUB_TASKS_LABEL"

# Auto-Fix Configuration
AUTOFIX_ENABLED="$AUTOFIX_ENABLED"
AUTOFIX_SCRIPTS="$AUTOFIX_SCRIPTS"
AUTOFIX_MAX_ATTEMPTS=$AUTOFIX_MAX_ATTEMPTS
AUTOFIX_BRANCH_PREFIX="$AUTOFIX_BRANCH_PREFIX"
EOF

    chmod 600 "$CONFIG_FILE"
}

save_msmtp_config() {
    # Sanitize password - remove any newlines that may have been accidentally included
    local clean_password="${SMTP_PASSWORD//$'\n'/}"
    clean_password="${clean_password//$'\r'/}"

    cat > "$MSMTP_CONFIG" << EOF
# msmtp configuration
# Generated by Pauly: $(date)

defaults
auth           on
tls            on
tls_trust_file /etc/ssl/cert.pem
logfile        ~/.msmtp.log

account        default
host           $SMTP_HOST
port           $SMTP_PORT
from           $EMAIL
user           $SMTP_USER
password       "$clean_password"
EOF

    chmod 600 "$MSMTP_CONFIG"
}

smtp_configured() {
    [ -n "$SMTP_USER" ] && [ -n "$SMTP_PASSWORD" ]
}

config_exists() {
    [ -f "$CONFIG_FILE" ] && [ -s "$CONFIG_FILE" ]
}

get_config_value() {
    local key="$1"
    load_config
    eval echo "\$$key"
}

# ==========================================
# Interactive Prompts
# ==========================================

prompt_value() {
    local prompt="$1"
    local default="$2"
    local value=""

    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " value
        echo "${value:-$default}"
    else
        read -p "$prompt: " value
        echo "$value"
    fi
}

prompt_yes_no() {
    local prompt="$1"
    local default="${2:-n}"
    local response=""

    if [ "$default" = "y" ]; then
        read -p "$prompt [Y/n]: " response
        response="${response:-y}"
    else
        read -p "$prompt [y/N]: " response
        response="${response:-n}"
    fi

    [[ "$response" =~ ^[Yy] ]]
}

prompt_password() {
    local prompt="$1"
    local password=""

    # -s hides input, -r prevents backslash interpretation
    read -s -r -p "$prompt: " password
    echo ""  # New line after hidden input
    echo "$password"
}

run_config_wizard() {
    echo ""
    echo "Pauly Configuration"
    echo "==================="
    echo ""

    load_config

    # Email
    echo "Email address to RECEIVE notifications and alerts."
    EMAIL=$(prompt_value "Send notifications to" "$EMAIL")
    echo ""

    # Projects directory
    echo "Directory containing your git repositories."
    PROJECTS_DIR=$(prompt_value "Projects directory" "$PROJECTS_DIR")
    echo ""

    # SMTP Configuration
    echo "SMTP Configuration (account to SEND emails from)"
    echo "-------------------------------------------------"
    echo ""

    # Default SMTP user to email if not set
    local smtp_user_default="${SMTP_USER:-$EMAIL}"
    SMTP_USER=$(prompt_value "Gmail address to send from" "$smtp_user_default")

    echo ""
    echo "Get an app password at: https://myaccount.google.com/apppasswords"
    echo "App password looks like: xxxx xxxx xxxx xxxx (16 chars with spaces)"

    # Password prompt (hidden input)
    if [ -n "$SMTP_PASSWORD" ]; then
        echo "App password is already set."
        if prompt_yes_no "Change app password?" "n"; then
            SMTP_PASSWORD=$(prompt_password "App password")
        fi
    else
        SMTP_PASSWORD=$(prompt_password "App password")
    fi

    echo ""
    echo "SMTP server settings (press Enter to accept defaults for Gmail):"
    SMTP_HOST=$(prompt_value "SMTP host" "$SMTP_HOST")
    SMTP_PORT=$(prompt_value "SMTP port" "$SMTP_PORT")
    echo ""

    # Email Tasks Configuration
    if prompt_yes_no "Enable email tasks? (send tasks via email)" "n"; then
        echo ""
        echo "Email Tasks Configuration"
        echo "-------------------------"
        echo "Send emails to have Pauly execute tasks automatically."
        echo "Only emails from allowed senders will be processed."
        echo ""

        IMAP_HOST=$(prompt_value "IMAP host" "$IMAP_HOST")
        IMAP_PORT=$(prompt_value "IMAP port" "$IMAP_PORT")

        # Default allowed senders to the configured email
        local allowed_default="${ALLOWED_SENDERS:-$EMAIL}"
        echo "Comma-separated list of email addresses allowed to send tasks."
        ALLOWED_SENDERS=$(prompt_value "Allowed senders" "$allowed_default")
        echo ""

        echo "Dev Mode via Email"
        echo "------------------"
        echo "To use 'pauly dev' commands via email, specify the project directory."
        echo "Use full path (e.g., /Users/username/Projects, not ~/Projects)"
        echo "Leave empty to disable email-triggered dev mode."
        DEV_PROJECT_DIR=$(prompt_value "Dev project directory" "${DEV_PROJECT_DIR:-$PROJECTS_DIR}")
        echo ""
    fi

    # GitHub Tasks Configuration
    if prompt_yes_no "Enable GitHub Issues tasks? (create issues to trigger tasks)" "n"; then
        echo ""
        echo "GitHub Tasks Configuration"
        echo "--------------------------"
        echo "Create issues in a repo to trigger Pauly tasks."
        echo "Use labels like 'project:myapp' to target specific projects."
        echo ""
        echo "Enter repo as: owner/repo (NOT the full URL)"
        echo "Example: tony-garand/pauly-tasks"
        GITHUB_TASKS_REPO=$(prompt_value "GitHub repo (owner/repo)" "$GITHUB_TASKS_REPO")
        GITHUB_TASKS_LABEL=$(prompt_value "Label to watch for" "$GITHUB_TASKS_LABEL")
        echo ""

        if [ -z "$DEV_PROJECT_DIR" ]; then
            echo "Default project directory for tasks without a project label."
            echo "Use full path (e.g., /Users/username/Projects, not ~/Projects)"
            DEV_PROJECT_DIR=$(prompt_value "Default project directory" "${DEV_PROJECT_DIR:-$PROJECTS_DIR}")
            echo ""
        fi
    fi

    # Auto-Fix Configuration
    if prompt_yes_no "Enable auto-fix? (creates PRs for code bugs when jobs fail)" "n"; then
        AUTOFIX_ENABLED="true"
        echo ""
        echo "Auto-Fix Configuration"
        echo "----------------------"
        echo "When a job fails, Pauly will analyze the error and attempt to"
        echo "create a PR with a fix if it detects a code bug."
        echo ""
        echo "Which scripts can trigger auto-fix?"
        echo "  'all' = all scripts, or comma-separated list (e.g., 'daily-claude-summary.sh,git-health-check.sh')"
        AUTOFIX_SCRIPTS=$(prompt_value "Scripts" "$AUTOFIX_SCRIPTS")
        AUTOFIX_MAX_ATTEMPTS=$(prompt_value "Max fix attempts per failure" "$AUTOFIX_MAX_ATTEMPTS")
        AUTOFIX_BRANCH_PREFIX=$(prompt_value "Branch prefix" "$AUTOFIX_BRANCH_PREFIX")
        echo ""
    else
        AUTOFIX_ENABLED="false"
    fi

    # Advanced settings
    if prompt_yes_no "Configure advanced settings?" "n"; then
        echo ""
        MAX_LOG_SIZE_MB=$(prompt_value "Max log size (MB)" "$MAX_LOG_SIZE_MB")
        MAX_LOG_FILES=$(prompt_value "Number of log files to keep" "$MAX_LOG_FILES")
        echo ""

        echo "Healthchecks.io URL for uptime monitoring (optional)."
        HEALTHCHECK_URL=$(prompt_value "Healthcheck URL" "$HEALTHCHECK_URL")
        echo ""
    fi

    # Save configs
    save_config
    save_msmtp_config

    # Configure mail to use msmtp
    local mailrc="$HOME/.mailrc"
    if ! grep -q "msmtp" "$mailrc" 2>/dev/null; then
        echo 'set sendmail="/opt/homebrew/bin/msmtp"' >> "$mailrc"
    fi

    echo ""
    echo "Configuration saved!"
    echo "  Pauly config: $CONFIG_FILE"
    echo "  SMTP config:  $MSMTP_CONFIG"
    echo ""

    # Show summary
    echo "Current settings:"
    echo "  Send to:      $EMAIL"
    echo "  Send from:    $SMTP_USER"
    echo "  SMTP host:    $SMTP_HOST:$SMTP_PORT"
    echo "  Projects:     $PROJECTS_DIR"
    echo "  Log size:     ${MAX_LOG_SIZE_MB}MB"
    echo "  Log files:    $MAX_LOG_FILES"
    if [ -n "$HEALTHCHECK_URL" ]; then
        echo "  Healthcheck:  $HEALTHCHECK_URL"
    fi
    echo ""
}

show_config() {
    if ! config_exists; then
        echo "No configuration found. Run 'pauly config' to set up."
        return 1
    fi

    load_config

    echo "Configuration: $CONFIG_FILE"
    echo ""
    echo "General:"
    echo "  Send to:      ${EMAIL:-<not set>}"
    echo "  Projects:     $PROJECTS_DIR"
    echo ""
    echo "SMTP (send from):"
    echo "  Host:         $SMTP_HOST:$SMTP_PORT"
    echo "  From:         ${SMTP_USER:-<not set>}"
    echo "  Password:     ${SMTP_PASSWORD:+****}"
    echo "  Config:       $MSMTP_CONFIG"
    echo ""
    echo "Logs:"
    echo "  Max size:     ${MAX_LOG_SIZE_MB}MB"
    echo "  Keep files:   $MAX_LOG_FILES"

    if [ -n "$ALLOWED_SENDERS" ]; then
        echo ""
        echo "Email Tasks:"
        echo "  IMAP:         $IMAP_HOST:$IMAP_PORT"
        echo "  Allowed:      $ALLOWED_SENDERS"
        if [ -n "$DEV_PROJECT_DIR" ]; then
            echo "  Dev project:  $DEV_PROJECT_DIR"
        fi
    fi

    if [ -n "$GITHUB_TASKS_REPO" ]; then
        echo ""
        echo "GitHub Tasks:"
        echo "  Repo:         $GITHUB_TASKS_REPO"
        echo "  Label:        $GITHUB_TASKS_LABEL"
    fi

    if [ -n "$HEALTHCHECK_URL" ]; then
        echo ""
        echo "Monitoring:"
        echo "  Healthcheck:  $HEALTHCHECK_URL"
    fi

    echo ""
    echo "Auto-Fix:"
    if [ "${AUTOFIX_ENABLED:-false}" = "true" ]; then
        echo "  Enabled:      yes"
        echo "  Scripts:      $AUTOFIX_SCRIPTS"
        echo "  Max attempts: $AUTOFIX_MAX_ATTEMPTS"
        echo "  Branch:       $AUTOFIX_BRANCH_PREFIX/<script>-<timestamp>"
    else
        echo "  Enabled:      no"
    fi
}

# Load config on source
load_config
