#!/bin/bash

# Configuration management for Pauly CLI

CONFIG_FILE="$HOME/.config/pauly/config"
CONFIG_DIR="$HOME/.config/pauly"

# Default values
DEFAULT_EMAIL=""
DEFAULT_PROJECTS_DIR="$HOME/Projects"
DEFAULT_MAX_LOG_SIZE_MB=10
DEFAULT_MAX_LOG_FILES=5
DEFAULT_HEALTHCHECK_URL=""

# SMTP defaults
DEFAULT_SMTP_HOST="smtp.gmail.com"
DEFAULT_SMTP_PORT=587
DEFAULT_SMTP_USER=""
DEFAULT_SMTP_PASSWORD=""

# SMTP config file
MSMTP_CONFIG="$HOME/.msmtprc"

# ==========================================
# Config File Management
# ==========================================

ensure_config_dir() {
    mkdir -p "$CONFIG_DIR"
}

load_config() {
    ensure_config_dir

    # Set defaults
    EMAIL="${DEFAULT_EMAIL}"
    PROJECTS_DIR="${DEFAULT_PROJECTS_DIR}"
    MAX_LOG_SIZE_MB="${DEFAULT_MAX_LOG_SIZE_MB}"
    MAX_LOG_FILES="${DEFAULT_MAX_LOG_FILES}"
    HEALTHCHECK_URL="${DEFAULT_HEALTHCHECK_URL}"

    # SMTP defaults
    SMTP_HOST="${DEFAULT_SMTP_HOST}"
    SMTP_PORT="${DEFAULT_SMTP_PORT}"
    SMTP_USER="${DEFAULT_SMTP_USER}"
    SMTP_PASSWORD="${DEFAULT_SMTP_PASSWORD}"

    # Load from file if exists
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
    fi
}

save_config() {
    ensure_config_dir

    cat > "$CONFIG_FILE" << EOF
# Pauly Configuration
# Generated: $(date)

# Email for notifications and alerts
EMAIL="$EMAIL"

# Directory to scan for git repos and projects
PROJECTS_DIR="$PROJECTS_DIR"

# Log rotation settings
MAX_LOG_SIZE_MB=$MAX_LOG_SIZE_MB
MAX_LOG_FILES=$MAX_LOG_FILES

# Healthchecks.io ping URL (optional)
HEALTHCHECK_URL="$HEALTHCHECK_URL"

# SMTP Configuration
SMTP_HOST="$SMTP_HOST"
SMTP_PORT=$SMTP_PORT
SMTP_USER="$SMTP_USER"
SMTP_PASSWORD="$SMTP_PASSWORD"
EOF

    chmod 600 "$CONFIG_FILE"
}

save_msmtp_config() {
    cat > "$MSMTP_CONFIG" << EOF
# msmtp configuration
# Generated by Pauly: $(date)

defaults
auth           on
tls            on
tls_trust_file /etc/ssl/cert.pem
logfile        ~/.msmtp.log

account        default
host           $SMTP_HOST
port           $SMTP_PORT
from           $EMAIL
user           $SMTP_USER
password       $SMTP_PASSWORD
EOF

    chmod 600 "$MSMTP_CONFIG"
}

smtp_configured() {
    [ -n "$SMTP_USER" ] && [ -n "$SMTP_PASSWORD" ]
}

config_exists() {
    [ -f "$CONFIG_FILE" ] && [ -s "$CONFIG_FILE" ]
}

get_config_value() {
    local key="$1"
    load_config
    eval echo "\$$key"
}

# ==========================================
# Interactive Prompts
# ==========================================

prompt_value() {
    local prompt="$1"
    local default="$2"
    local value=""

    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " value
        echo "${value:-$default}"
    else
        read -p "$prompt: " value
        echo "$value"
    fi
}

prompt_yes_no() {
    local prompt="$1"
    local default="${2:-n}"
    local response=""

    if [ "$default" = "y" ]; then
        read -p "$prompt [Y/n]: " response
        response="${response:-y}"
    else
        read -p "$prompt [y/N]: " response
        response="${response:-n}"
    fi

    [[ "$response" =~ ^[Yy] ]]
}

prompt_password() {
    local prompt="$1"
    local password=""

    # -s hides input, -r prevents backslash interpretation
    read -s -r -p "$prompt: " password
    echo ""  # New line after hidden input
    echo "$password"
}

run_config_wizard() {
    echo ""
    echo "Pauly Configuration"
    echo "==================="
    echo ""

    load_config

    # Email
    echo "Email address for notifications and alerts."
    EMAIL=$(prompt_value "Email" "$EMAIL")
    echo ""

    # Projects directory
    echo "Directory containing your git repositories."
    PROJECTS_DIR=$(prompt_value "Projects directory" "$PROJECTS_DIR")
    echo ""

    # SMTP Configuration
    echo "SMTP Configuration (for sending emails)"
    echo "----------------------------------------"
    echo "Default is Gmail. Get an app password at:"
    echo "https://myaccount.google.com/apppasswords"
    echo ""

    SMTP_HOST=$(prompt_value "SMTP host" "$SMTP_HOST")
    SMTP_PORT=$(prompt_value "SMTP port" "$SMTP_PORT")

    # Default SMTP user to email if not set
    local smtp_user_default="${SMTP_USER:-$EMAIL}"
    SMTP_USER=$(prompt_value "SMTP username" "$smtp_user_default")

    # Password prompt (hidden input)
    if [ -n "$SMTP_PASSWORD" ]; then
        echo "SMTP password is already set."
        if prompt_yes_no "Change password?" "n"; then
            SMTP_PASSWORD=$(prompt_password "SMTP password (app password)")
        fi
    else
        SMTP_PASSWORD=$(prompt_password "SMTP password (app password)")
    fi
    echo ""

    # Advanced settings
    if prompt_yes_no "Configure advanced settings?" "n"; then
        echo ""
        MAX_LOG_SIZE_MB=$(prompt_value "Max log size (MB)" "$MAX_LOG_SIZE_MB")
        MAX_LOG_FILES=$(prompt_value "Number of log files to keep" "$MAX_LOG_FILES")
        echo ""

        echo "Healthchecks.io URL for uptime monitoring (optional)."
        HEALTHCHECK_URL=$(prompt_value "Healthcheck URL" "$HEALTHCHECK_URL")
        echo ""
    fi

    # Save configs
    save_config
    save_msmtp_config

    # Configure mail to use msmtp
    local mailrc="$HOME/.mailrc"
    if ! grep -q "msmtp" "$mailrc" 2>/dev/null; then
        echo 'set sendmail="/opt/homebrew/bin/msmtp"' >> "$mailrc"
    fi

    echo ""
    echo "Configuration saved!"
    echo "  Pauly config: $CONFIG_FILE"
    echo "  SMTP config:  $MSMTP_CONFIG"
    echo ""

    # Show summary
    echo "Current settings:"
    echo "  Email:        $EMAIL"
    echo "  Projects:     $PROJECTS_DIR"
    echo "  SMTP host:    $SMTP_HOST:$SMTP_PORT"
    echo "  SMTP user:    $SMTP_USER"
    echo "  SMTP pass:    ****"
    echo "  Log size:     ${MAX_LOG_SIZE_MB}MB"
    echo "  Log files:    $MAX_LOG_FILES"
    if [ -n "$HEALTHCHECK_URL" ]; then
        echo "  Healthcheck:  $HEALTHCHECK_URL"
    fi
    echo ""
}

show_config() {
    if ! config_exists; then
        echo "No configuration found. Run 'pauly config' to set up."
        return 1
    fi

    load_config

    echo "Configuration: $CONFIG_FILE"
    echo ""
    echo "General:"
    echo "  Email:        ${EMAIL:-<not set>}"
    echo "  Projects:     $PROJECTS_DIR"
    echo ""
    echo "SMTP:"
    echo "  Host:         $SMTP_HOST:$SMTP_PORT"
    echo "  User:         ${SMTP_USER:-<not set>}"
    echo "  Password:     ${SMTP_PASSWORD:+****}"
    echo "  Config:       $MSMTP_CONFIG"
    echo ""
    echo "Logs:"
    echo "  Max size:     ${MAX_LOG_SIZE_MB}MB"
    echo "  Keep files:   $MAX_LOG_FILES"
    if [ -n "$HEALTHCHECK_URL" ]; then
        echo ""
        echo "Monitoring:"
        echo "  Healthcheck:  $HEALTHCHECK_URL"
    fi
}

# Load config on source
load_config
